const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {PGlite}=require('@electric-sql/pglite');
const sql=fs.readFileSync(path.join(__dirname,'../../sql/add-audit-restore.sql'),'utf8');
const comm=fs.readFileSync(path.join(__dirname,'../../sql/add-patient-communications.sql'),'utf8');
const PAT='11111111-1111-4111-8111-111111111111',OTHER='22222222-2222-4222-8222-222222222222',RID='44444444-4444-4444-8444-444444444444';let db;
async function latest(table='patients',op='UPDATE'){return (await db.query('select audit_id from clinic_private.audit_recovery where table_name=$1 and operation=$2 order by audit_id',[table,op])).rows.at(-1)?.audit_id;}
async function preview(id){return (await db.query('select public.audit_restore_preview($1) p',[id])).rows[0].p;}
async function apply(id,keys=[]){return (await db.query('select public.audit_restore_apply($1,$2,$3) p',[id,keys,'Correct mistaken entry'])).rows[0].p;}
test.before(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create schema private;
 grant usage on schema auth,private to authenticated;
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql as $$select jsonb_build_object('email','test.nurse@example.test','is_anonymous',false)$$;
 create function private.is_clinic_member() returns boolean language sql as $$select auth.uid() is not null and coalesce(current_setting('test.member',true),'true')='true'$$;
 create table public.patients(id uuid primary key,first_name text,surname text,notes text,ward text,visible boolean default true,is_inpatient boolean default false,updated_at timestamptz);
 create table public.audit_log(id uuid primary key default gen_random_uuid(),at timestamptz default clock_timestamp(),actor text,actor_email text,action text,entity text,entity_id text,patient_id text,patient_name text,summary text,details jsonb);
 create table public.encounters(id uuid primary key,patient_id text,assessment jsonb,nursing_report text);
 create table public.appointments(id uuid primary key,patient_id uuid references patients(id) on delete cascade,notes text);
 create table public.siting_sessions(id uuid primary key,patient_id uuid references patients(id) on delete set null,notes text);
 create table public.siting_images(siting_id uuid primary key references siting_sessions(id) on delete cascade,image_data text);
 grant select,insert,update,delete on all tables in schema public to authenticated;
 alter table patients enable row level security;create policy clinic on patients to authenticated using(private.is_clinic_member() and visible) with check(private.is_clinic_member() and visible);
 alter table audit_log enable row level security;create policy clinic on audit_log to authenticated using(private.is_clinic_member());
 alter table encounters enable row level security;create policy clinic on encounters to authenticated using(private.is_clinic_member());
 `);await db.exec(comm);await db.exec('grant delete on patient_communications to authenticated; create policy restore_delete on patient_communications for delete to authenticated using(private.is_clinic_member())');await db.exec(sql);await db.exec(sql);});
test.beforeEach(async()=>{await db.exec("reset role;select set_config('test.uid','',false);truncate audit_log,patients,encounters,appointments,siting_sessions,siting_images,patient_communications cascade;");await db.query("insert into patients(id,first_name,surname,notes,ward) values($1,'Alex','Sample','Original','SW1'),($2,'Other','Sample','Unrelated','SW2')",[PAT,OTHER]);await db.exec("select set_config('test.uid','33333333-3333-4333-8333-333333333333',false),set_config('test.member','true',false);set role authenticated;");});
test.after(()=>db.close());
test('selected restore preserves unrelated later fields and captures compact trusted changes',async()=>{await db.query("update patients set notes='Mistake',ward='SW3' where id=$1",[PAT]);const id=await latest();await db.query("update patients set first_name='Alexis' where id=$1",[PAT]);const p=await preview(id);assert.deepEqual(p.records[0].fields.map(f=>f.key).sort(),['notes','ward']);assert.equal((await apply(id,['notes'])).restored_records,1);const r=(await db.query('select * from patients where id=$1',[PAT])).rows[0];assert.equal(r.notes,'Original');assert.equal(r.ward,'SW3');assert.equal(r.first_name,'Alexis');await assert.rejects(apply(id,['notes']),/Already-restored|Select an available/);});
test('later edits and ABA values block a stale restore atomically',async()=>{await db.query("update patients set notes='Mistake',ward='SW3' where id=$1",[PAT]);const id=await latest();await db.query("update patients set notes='Newer' where id=$1",[PAT]);await assert.rejects(apply(id,['ward','notes']),/changed again|later change/i);assert.equal((await db.query('select ward from patients where id=$1',[PAT])).rows[0].ward,'SW3');await db.query("update patients set notes='Mistake' where id=$1",[PAT]);await assert.rejects(apply(id,['notes']),/later change/i);});
test('expired recovery and untrusted field selection cannot change records',async()=>{await db.query("update patients set notes='Mistake' where id=$1",[PAT]);const id=await latest();await assert.rejects(apply(id,['id']),/Invalid field/);await db.exec('reset role');await db.query("update audit_log set at=now()-interval '91 days' where id=$1",[id]);await db.exec('set role authenticated');await assert.rejects(preview(id),/expired/);await assert.rejects(apply(id,['notes']),/expired/);});
test('deletion restoration includes cascades and SET NULL companions but excludes unrelated bulk deletes',async()=>{await db.query('insert into appointments values($1,$2,$3)',[RID,PAT,'Review']);await db.query('insert into siting_sessions values($1,$2,$3)',[RID,PAT,'Siting']);await db.query('delete from patients where id in ($1,$2)',[PAT,OTHER]);const id=(await db.query("select audit_id from clinic_private.audit_recovery where table_name='patients' and pk_value=$1 and operation='DELETE'",[PAT])).rows[0].audit_id;const p=await preview(id);assert.equal(p.records.length,3);assert.equal((await apply(id)).restored_records,3);assert.equal((await db.query('select count(*)::int n from patients')).rows[0].n,1);assert.equal((await db.query('select patient_id from siting_sessions')).rows[0].patient_id,PAT);assert.equal((await db.query('select notes from appointments')).rows[0].notes,'Review');});
test('missing parent, reused IDs and photograph backups refuse partial restoration',async()=>{await db.query('insert into appointments values($1,$2,$3)',[RID,PAT,'Review']);await db.query('delete from appointments where id=$1',[RID]);const id=await latest('appointments','DELETE');await db.query('delete from patients where id=$1',[PAT]);await assert.rejects(apply(id),/required related record/i);await db.query('insert into siting_sessions values($1,null,$2)',[RID,'Siting']);await db.query('insert into siting_images values($1,$2)',[RID,'image payload']);await db.query('delete from siting_sessions where id=$1',[RID]);const sid=await latest('siting_sessions','DELETE');await assert.rejects(apply(sid),/excluded photograph/);assert.equal((await db.query('select count(*)::int n from siting_sessions')).rows[0].n,0);});
test('encounter restore appends a signed version and excludes historical version arrays from edit backups',async()=>{const one={schema:2,current_version:1,snapshot:{notes:'Original'},versions:[{version:1,report:'Original report',snapshot:{notes:'Original'}}]};await db.query('insert into encounters values($1,$2,$3,$4)',[RID,PAT,JSON.stringify(one),'Original report']);const two={...one,current_version:2,snapshot:{notes:'Mistake'},versions:[...one.versions,{version:2,report:'Mistake report'}]};await db.query('update encounters set assessment=$1,nursing_report=$2 where id=$3',[JSON.stringify(two),'Mistake report',RID]);const id=await latest('encounters');const p=await preview(id);assert.equal(p.records[0].fields.find(f=>f.key==='assessment').before.versions,undefined);await assert.rejects(apply(id,['assessment']),/together/);await apply(id,['assessment','nursing_report']);const row=(await db.query('select * from encounters')).rows[0];assert.equal(row.assessment.current_version,3);assert.equal(row.assessment.versions.length,3);assert.equal(row.assessment.versions[1].report,'Mistake report');assert.equal(row.nursing_report,'Original report');assert.equal(row.assessment.versions[2].author_name,'Test Nurse');});
async function saveCommunication(){return (await db.query('select save_patient_communication($1,$2,0,$3,$4) r',[PAT,RID,'patient',JSON.stringify({communication_date:'2026-10-09',method:'Telephone',direction:'Incoming',contact_name:'Alex',service:'',subject:'Advice',notes:'Original advice',status:'Recorded'})])).rows[0].r;}
test('communication edits and deleted communications retain authentic signatures and add a new version',async()=>{const one=await saveCommunication();await db.query("update patient_communications set notes='Mistake' where id=$1",[RID]);const edit=await latest('patient_communications');await apply(edit,['notes']);let row=(await db.query('select * from patient_communications')).rows[0];assert.equal(row.version,3);assert.equal(row.versions.length,3);assert.equal(row.notes,'Original advice');await db.query('delete from patient_communications where id=$1',[RID]);const deleted=await latest('patient_communications','DELETE');await apply(deleted);row=(await db.query('select * from patient_communications')).rows[0];assert.equal(row.version,4);assert.equal(row.versions.length,4);assert.equal(row.created_at.toISOString(),new Date(one.created_at).toISOString());assert.equal(row.versions[1].snapshot.notes,'Mistake');});
test('journal is read-only, clinic access is required, and deleting the audit entry deletes its backup',async()=>{await db.query("update patients set notes='Mistake' where id=$1",[PAT]);const id=await latest();await assert.rejects(db.exec('delete from clinic_private.audit_recovery'),/permission denied/);await assert.rejects(db.exec("insert into clinic_private.audit_recovery(audit_id) values(gen_random_uuid())"),/permission denied/);await db.exec("select set_config('test.member','false',false)");await assert.rejects(preview(id),/sign-in required/);await assert.rejects(apply(id,['notes']),/sign-in required/);await db.exec("select set_config('test.member','true',false)");await db.query('delete from audit_log where id=$1',[id]);assert.equal((await db.query('select count(*)::int n from clinic_private.audit_recovery')).rows[0].n,0);await db.exec('reset role;set role anon');await assert.rejects(preview(id),/permission denied/);await assert.rejects(apply(id,['notes']),/permission denied/);});
test('missing child recovery blocks its parent deletion, and same-transaction ABA is detected',async()=>{await db.query('insert into appointments values($1,$2,$3)',[RID,PAT,'Review']);await db.query('delete from patients where id=$1',[PAT]);const parent=(await db.query("select audit_id from clinic_private.audit_recovery where table_name='patients' and pk_value=$1",[PAT])).rows[0].audit_id;const child=await latest('appointments','DELETE');await db.query('delete from audit_log where id=$1',[child]);await assert.rejects(apply(parent),/related recovery entry is missing/);assert.equal((await db.query('select count(*)::int n from patients where id=$1',[PAT])).rows[0].n,0);await db.exec('begin');await db.query("update patients set notes='Mistake' where id=$1",[OTHER]);const original=(await db.query("select audit_id from clinic_private.audit_recovery where table_name='patients' and pk_value=$1 order by sequence desc limit 1",[OTHER])).rows[0].audit_id;await db.query("update patients set notes='Second' where id=$1",[OTHER]);await db.query("update patients set notes='Mistake' where id=$1",[OTHER]);await db.exec('commit');await assert.rejects(apply(original,['notes']),/later change/i);});
test('deleting a patient with a signed issue and contact restores both histories in dependency order',async()=>{await saveCommunication();const contact='55555555-5555-4555-8555-555555555555';await db.query("insert into patient_communications(id,patient_id,kind,parent_id,communication_date,method,direction,contact_name,subject,notes,status) values($1,$2,'patient',$3,'2026-10-10','Telephone','Incoming','Alex','Follow up','Original contact','Recorded')",[contact,PAT,RID]);await db.query("update patient_communications set status='Completed' where id=$1",[RID]);await db.query('delete from patients where id=$1',[PAT]);const id=(await db.query("select audit_id from clinic_private.audit_recovery where table_name='patients' and pk_value=$1 and operation='DELETE'",[PAT])).rows[0].audit_id;await apply(id);const rows=(await db.query('select * from patient_communications order by parent_id nulls first')).rows;assert.equal(rows.length,2);assert.equal(rows[0].status,'Completed');assert.equal(rows[0].version,4);assert.equal(rows[1].version,2);assert.equal(rows[1].versions[0].snapshot.notes,'Original contact');assert.equal(rows[1].parent_id,RID);});
