const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const {boot}=require('./jason-encounters.fixture.cjs');
const script=fs.readFileSync(path.join(__dirname,'../../assets/jason-encounters.js'),'utf8');
const plain=x=>JSON.parse(JSON.stringify(x));
const tick=()=>new Promise(r=>setTimeout(r,0));
function setup(t){const dom=new JSDOM('<div id="app"><main class="main"><section id="page-handover" class="page active"><table><tr><td>All patients</td></tr></table></section></main></div>',{runScripts:'outside-only',url:'https://example.test'});t.after(()=>dom.window.close());boot(dom.window);dom.window.eval(script);return dom.window;}
function change(w,selector,value){const el=w.document.querySelector(selector);assert.ok(el,selector);if(el.type==='checkbox')el.checked=value;else el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}));}
function notes(w,text,box='jenc-notes-0'){const el=w.document.getElementById(box);el.value=text;el.dispatchEvent(new w.Event('input',{bubbles:true}));}
function click(w,action,extra=''){const el=w.document.querySelector('[data-action="'+action+'"]'+extra);assert.ok(el,action);el.click();}

test('only the verified Jason profile can open the new workspace',async t=>{const w=setup(t);w.fixture.email='other@example.test';await w.JasonEncounters.open(w.fixture.patient.id);assert.equal(w.fixture.reads,0);assert.equal(w.JasonEncounters.state,null);w.fixture.email='jason.fenech@gov.mt';w.fixture.enabled=false;await w.JasonEncounters.open(w.fixture.patient.id);assert.equal(w.fixture.reads,0);});

test('opening preserves the full handover table and collapses the current appliance setup',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);assert.ok(w.document.querySelector('#page-handover table'));assert.ok(w.document.body.classList.contains('jenc-open'));const ap=w.document.querySelector('[data-section="appliances:stoma-one"]');assert.equal(ap.open,false);assert.match(ap.textContent,/Drainable pouch/);assert.match(ap.textContent,/Current setup · no changes/);assert.ok(w.document.querySelector('#jenc-notes-0'));assert.doesNotMatch(w.document.querySelector('#page-jason-encounters').textContent,/Assigned nurse/);});

test('each stoma retains its own assessment, output and appliance selection',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-kind="stoma"][data-field="colour"][data-uid="stoma-one"]','Healthy pink');change(w,'[data-field="output"][data-uid="stoma-one"][value="Flatus present"]',true);change(w,'[data-kind="stoma"][data-field="colour"][data-uid="stoma-two"]','Dusky');change(w,'[data-field="output"][data-uid="stoma-two"][value="Hemoserous fluid"]',true);const s=w.JasonEncounters.state.draft.stomas;assert.equal(s[0].colour,'Healthy pink');assert.deepEqual(plain(s[0].output),['Flatus present']);assert.equal(s[1].colour,'Dusky');assert.deepEqual(plain(s[1].output),['Hemoserous fluid']);assert.deepEqual(plain(s[0].appliances),['Drainable pouch']);assert.deepEqual(plain(s[1].appliances),['Urostomy pouch']);assert.equal(w.document.querySelector('[data-kind="rod"][data-field="present"][data-uid="stoma-one"]').checked,true);assert.equal(w.document.querySelector('[data-kind="rod"][data-uid="stoma-two"]'),null);});

test('Nil is exclusive, other outputs can be combined, and the dropdown stays open',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-field="output"][value="Liquid stools"]',true);change(w,'[data-field="output"][value="Flatus present"]',true);assert.deepEqual(plain(w.JasonEncounters.state.draft.stomas[0].output),['Liquid stools','Flatus present']);change(w,'[data-field="output"][value="Nil"]',true);assert.deepEqual(plain(w.JasonEncounters.state.draft.stomas[0].output),['Nil']);change(w,'[data-field="output"][value="Blood"]',true);assert.deepEqual(plain(w.JasonEncounters.state.draft.stomas[0].output),['Blood']);assert.equal(w.document.querySelector('[data-field="output"]').closest('details').open,true);});

test('each stoma keeps its own notes, saved with the episode and every stoma, with automatic signature and no appliance writes',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);notes(w,'Patient comfortable.\nTeaching given <today>.');notes(w,'Urine clear.','jenc-notes-1');await w.JasonEncounters.save();const args=w.fixture.calls[0].args;assert.equal(args.p_episode_id,w.fixture.episode.id);assert.deepEqual(args.p_snapshot.scope,['stoma-one','stoma-two']);assert.equal(args.p_snapshot.stomas[0].notes,'Patient comfortable.\nTeaching given <today>.');assert.equal(args.p_snapshot.stomas[1].notes,'Urine clear.');assert.match(args.p_report,/Loop Ileostomy notes: Patient comfortable/);assert.match(args.p_report,/Urostomy notes: Urine clear\./);assert.doesNotMatch(args.p_report,/\bS[12]\b/);assert.deepEqual(args.p_impact.appliances,[]);assert.deepEqual(args.p_impact.patient_patch,{});assert.equal(w.JasonEncounters.state.editable,false);assert.match(w.document.querySelector('.jenc-signature').textContent,/Signed by: Jason Fenech/);assert.equal(w.document.querySelector('#jenc-report today'),null);});

test('editing saved wording and a dropdown makes V2 on the same encounter with only changes red',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-field="colour"]','Healthy pink');notes(w,'Patient comfotable today.');await w.JasonEncounters.save();const id=w.JasonEncounters.state.record.id;click(w,'edit');notes(w,'Patient comfortable today.');change(w,'[data-field="colour"]','Dusky');assert.equal(w.document.querySelector('.jenc-note-mirror .jenc-change').textContent,'comfortable');assert.ok(w.document.querySelector('[data-field="colour"]').classList.contains('jenc-changed'));assert.match(w.document.querySelector('.jenc-note-diff del').textContent,/comfotable/);await w.JasonEncounters.save();const state=w.JasonEncounters.state;assert.equal(state.record.id,id);assert.equal(state.record.assessment.versions.length,2);assert.equal(state.record.assessment.versions[0].snapshot.stomas[0].notes,'Patient comfotable today.');assert.equal(state.record.assessment.versions[0].snapshot.stomas[0].colour,'Healthy pink');assert.equal(w.fixture.calls[1].args.p_encounter_id,id);assert.equal(w.fixture.calls[1].args.p_expected_version,1);assert.equal(state.expectedVersion,2);click(w,'version','[data-index="0"]');assert.equal(w.document.getElementById('jenc-notes-0').value,'Patient comfotable today.');assert.equal(w.document.querySelector('[data-field="colour"]').value,'Healthy pink');assert.equal(w.document.querySelector('.jenc-note-mirror .jenc-change'),null);click(w,'version','[data-index="1"]');assert.equal(w.document.querySelector('.jenc-note-mirror .jenc-change').textContent,'comfortable');assert.equal(w.document.querySelectorAll('#jenc-report .jenc-change').length>0,true);});

test('a failed save keeps the editable draft and leaves appliances untouched for retry',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);notes(w,'Keep this draft.');w.fixture.failSave=true;await w.JasonEncounters.save();assert.equal(w.JasonEncounters.state.editable,true);assert.equal(w.document.getElementById('jenc-notes-0').value,'Keep this draft.');assert.match(w.document.querySelector('[role="alert"]').textContent,/changes remain/);assert.equal(w.document.getElementById('jenc-save').disabled,false);assert.equal(w.fixture.records.length,0);assert.deepEqual(w.fixture.calls[0].args.p_impact.appliances,[]);});

test('an appliance edit affects one stoma, and a two-piece system requires both pieces',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-field="pouch"]','Convex drainable pouch');await w.JasonEncounters.save();assert.equal(w.fixture.calls[0].args.p_impact.appliances.length,1);assert.equal(w.fixture.calls[0].args.p_impact.appliances[0].stoma_uid,'stoma-one');assert.deepEqual(w.fixture.calls[0].args.p_snapshot.stomas[1].appliances,['Urostomy pouch']);click(w,'edit');change(w,'[data-field="system"]','two');change(w,'[data-field="baseplate"]','Baseplate 57 mm');await w.JasonEncounters.save();assert.equal(w.fixture.calls.length,1);assert.match(w.document.querySelector('[role="alert"]').textContent,/both the baseplate and pouch/);});

test('patient infection, episode support and per-stoma complications all enter the saved report',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-kind="infection"][data-field="status"]','Infection');change(w,'[data-kind="infection"][data-field="organism"]','CRE');click(w,'add-referral');change(w,'[data-kind="referral"][data-field="profession"]','Psychologist');change(w,'[data-kind="referral"][data-field="status"]','Seen');click(w,'add-comp');change(w,'[data-kind="comp"][data-field="text"]','Retraction');await w.JasonEncounters.save();const a=w.fixture.calls[0].args;assert.match(a.p_report,/CRE · Infection/);assert.match(a.p_report,/Psychologist: seen/);assert.match(a.p_report,/Retraction: active/);const comps=JSON.parse(a.p_impact.patient_patch.complications);assert.equal(comps[0].stoma_uid,'stoma-one');assert.equal(a.p_snapshot.stomas[1].complications.length,0);});

test('unchanged edits create no extra version and read-only history still allows filtering',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);notes(w,'Assessment complete.');await w.JasonEncounters.save();click(w,'edit');await w.JasonEncounters.save();assert.equal(w.fixture.calls.length,1);assert.match(w.document.querySelector('[role="alert"]').textContent,/no changes/);click(w,'cancel');click(w,'history');const filter=w.document.querySelector('[data-kind="history"]');assert.equal(filter.disabled,false);change(w,'[data-kind="history"]','all');assert.equal(w.document.querySelectorAll('[data-action="view"]').length,1);});

test('Jason handover retains status summaries and print values with only the Encounter care action',t=>{const w=setup(t);w.applianceLineIsTwoPiece=()=>true;w.handoverComplicationLine=()=> 'Retraction';w.fixture.patient.flange_due='2026-10-07';w.fixture.patient.inpatient_nurse_notes='CRE · Infection';const cell=w.JasonEncounters.handoverCell(w.fixture.patient,'Two-piece pouch');const el=w.document.createElement('div');el.innerHTML=cell;assert.equal(el.querySelectorAll('button').length,1);assert.match(el.querySelector('button').textContent,/Encounter/);assert.equal(el.querySelector('.hv-appl').tagName,'SPAN');assert.equal(el.querySelector('.hv-appl').getAttribute('onclick'),null);assert.equal(el.querySelector('.hv-flange-date').type,'hidden');assert.equal(el.querySelector('.hv-flange-date').value,'2026-10-07');assert.equal(el.querySelector('.hv-note').value,'CRE · Infection');assert.equal(el.querySelector('.hv-cmp-line').textContent,'Retraction');});

test('a discharged patient can still open, read and correct saved encounter history',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);notes(w,'Before discharge.');await w.JasonEncounters.save();w.fixture.episode.is_current=false;w.fixture.episode.discharge_date='2026-10-05';await w.JasonEncounters.open(w.fixture.patient.id);assert.equal(w.JasonEncounters.state.mode,'history');assert.equal(w.document.querySelector('[data-action="new"]'),null);click(w,'view');assert.equal(w.document.getElementById('jenc-notes-0').value,'Before discharge.');click(w,'edit');notes(w,'Corrected before discharge.');await w.JasonEncounters.save();assert.equal(w.JasonEncounters.state.record.assessment.versions.length,2);assert.equal(w.JasonEncounters.state.rows.length,1);});

test('a new encounter preserves resolved infection status and never invents CRE from unrelated notes',async t=>{const w=setup(t);w.fixture.patient.inpatient_nurse_notes='Infection status: Resolved';await w.JasonEncounters.open(w.fixture.patient.id);assert.deepEqual(plain(w.JasonEncounters.state.draft.infection),{status:'Resolved',organism:''});w.fixture.patient.inpatient_nurse_notes='Serous secretion, other accessories discussed.';await w.JasonEncounters.open(w.fixture.patient.id);assert.deepEqual(plain(w.JasonEncounters.state.draft.infection),{status:'Not recorded',organism:''});w.fixture.patient.inpatient_nurse_notes='CRE · Colonisation';await w.JasonEncounters.open(w.fixture.patient.id);assert.deepEqual(plain(w.JasonEncounters.state.draft.infection),{status:'Colonisation',organism:'CRE'});});

test('every stoma has its own column named by type, with no S-numbers, tabs or notes dropdown',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);const page=w.document.querySelector('#page-jason-encounters');
  const titles=sel=>Array.from(page.querySelectorAll('[data-step="'+sel+'"] .jenc-stoma-title'),h=>h.textContent);
  assert.deepEqual(titles('review'),['Loop Ileostomy','Urostomy']);assert.deepEqual(titles('appliances'),['Loop Ileostomy','Urostomy']);
  assert.deepEqual(Array.from(page.querySelectorAll('[data-step="report"] .jenc-notes-label'),l=>l.textContent),['Loop Ileostomy — clinical notes','Urostomy — clinical notes']);
  assert.equal(page.querySelectorAll('[data-kind="stoma"][data-field="colour"]').length,2);assert.equal(page.querySelectorAll('[data-section^="complications:"]').length,2);
  assert.equal(page.querySelector('[data-action="stoma"]'),null);assert.equal(page.querySelector('[data-kind="global"]'),null);assert.equal(page.querySelector('#jenc-notes'),null);
  assert.doesNotMatch(page.textContent,/\bS[12]\b/);
  click(w,'add-comp','[data-uid="stoma-two"]');change(w,'[data-kind="comp"][data-uid="stoma-two"][data-field="text"]','Retraction');const s=w.JasonEncounters.state.draft.stomas;assert.equal(s[0].complications.length,0);assert.equal(s[1].complications[0].text,'Retraction');});

test('an older encounter with one set of episode notes still shows them as General notes',async t=>{const w=setup(t);
  const snap={stomas:[{uid:'stoma-one',number:'S1',type:'Loop ileostomy',colour:'',output:['Gas'],appliances:['Drainable pouch'],accessories:[],complications:[],rod:{status:'Not recorded'}},{uid:'stoma-two',number:'S2',type:'Urostomy',colour:'',output:[],appliances:['Urostomy pouch'],accessories:[],complications:[],rod:{status:'Not recorded'}}],scope:['stoma-one'],notes:'Old episode notes.',infection:{status:'Not recorded',organism:''},referrals:[]};
  w.fixture.records.push({id:'44444444-4444-4444-8444-444444444444',patient_id:w.fixture.patient.id,episode_id:w.fixture.episode.id,episode_ref:'EP-DEMO',encounter_date:'2026-10-04',created_at:'2026-10-04T10:00:00Z',created_by_name:'Jason Fenech',assessment:{schema:2,current_version:1,snapshot:snap,versions:[{version:1,saved_at:'2026-10-04T10:00:00Z',author_name:'Jason Fenech',snapshot:snap,report:'S1 — Loop ileostomy: function / output: Gas.\nNotes: Old episode notes.'}]}});
  await w.JasonEncounters.open(w.fixture.patient.id);click(w,'history');click(w,'view');
  assert.equal(w.document.getElementById('jenc-notes').value,'Old episode notes.');assert.match(w.document.querySelector('label[for="jenc-notes"]').textContent,/General notes/);
  assert.match(w.document.getElementById('jenc-report').textContent,/S1 — Loop ileostomy/);assert.match(w.document.querySelector('[data-field="output"][data-uid="stoma-one"]').closest('details').textContent,/Gas/);
  click(w,'edit');assert.deepEqual(plain(w.JasonEncounters.state.draft.scope),['stoma-one','stoma-two']);await w.JasonEncounters.save();assert.match(w.document.querySelector('[role="alert"]').textContent,/no changes/);});

test('an encounter is coded ENC-ID-date, and reopening it the same day continues it as V2',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);notes(w,'Morning review.');await w.JasonEncounters.save();
  assert.match(w.document.querySelector('.jenc-version strong').textContent,/^ENC-DEMO-001-051026 · V1$/);assert.match(w.document.querySelector('[role="status"]').textContent,/ENC-DEMO-001-051026 saved · V1/);
  await w.JasonEncounters.open(w.fixture.patient.id);const s=w.JasonEncounters.state;assert.equal(s.editable,true);assert.equal(s.record.id,w.fixture.records[0].id);assert.equal(w.document.getElementById('jenc-notes-0').value,'Morning review.');
  assert.match(w.document.querySelector('[role="status"]').textContent,/already saved — your changes will be saved as V2/);
  notes(w,'Morning review. Afternoon: output increased.');await w.JasonEncounters.save();assert.equal(w.fixture.records.length,1);assert.equal(w.fixture.calls[1].args.p_encounter_id,w.fixture.records[0].id);assert.equal(w.JasonEncounters.state.record.assessment.versions.length,2);
  assert.equal(w.JasonEncounters.code({id:'b',encounter_date:'2026-10-05',created_at:'2026-10-05T12:00:00Z'},w.fixture.patient,[{id:'a',encounter_date:'2026-10-05',created_at:'2026-10-05T09:00:00Z'},{id:'b',encounter_date:'2026-10-05',created_at:'2026-10-05T12:00:00Z'}]),'ENC-DEMO-001-051026-2');
  await w.JasonEncounters.open(w.fixture.patient.id,w.fixture.records[0].id);assert.equal(w.JasonEncounters.state.editable,false);assert.equal(w.JasonEncounters.state.viewVersion.version,2);});

test('only a loop stoma offers the Rod present tick; it shows the removal date and unticking records removal',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);const q=x=>w.document.querySelector(x);
  assert.equal(q('[data-kind="rod"][data-uid="stoma-two"]'),null);assert.equal(q('[data-kind="rod"][data-field="present"][data-uid="stoma-one"]').checked,true);
  assert.equal(q('[data-kind="rod"][data-field="due"][data-uid="stoma-one"]').value,'2026-10-07');
  assert.doesNotMatch(q('[data-section="complications:stoma-one"] summary').textContent,/rod/i);
  change(w,'[data-kind="rod"][data-field="due"][data-uid="stoma-one"]','');await w.JasonEncounters.save();assert.match(q('[role="alert"]').textContent,/planned rod removal date/);assert.equal(w.fixture.calls.length,0);
  change(w,'[data-kind="rod"][data-field="due"][data-uid="stoma-one"]','2026-10-07');
  change(w,'[data-kind="rod"][data-field="present"][data-uid="stoma-one"]',false);assert.equal(w.JasonEncounters.state.draft.stomas[0].rod.status,'Removed');assert.equal(q('[data-kind="rod"][data-field="removed"][data-uid="stoma-one"]').value,'2026-10-05');
  await w.JasonEncounters.save();const a=w.fixture.calls[0].args;assert.deepEqual(plain(a.p_impact.patient_patch),{rod_stoma_uid:'stoma-one',rod_removal_date:'2026-10-07',rod_removed_date:'2026-10-05'});assert.match(a.p_report,/Loop Ileostomy — .*rod removed 2026-10-05/);
  for(const type of ['End colostomy','End ileostomy','Urostomy'])assert.equal(w.JasonEncounters.rodCapable(type),false,type);});

test('peristomal skin: Not healthy asks which problem, and each problem becomes a complication of that stoma; Healthy resolves it',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);const q=x=>w.document.querySelector(x);
  assert.equal(q('[data-kind="skin"][data-field="problems"]'),null);
  change(w,'[data-kind="skin"][data-field="status"][data-uid="stoma-two"]','Not healthy');assert.ok(q('[data-kind="skin"][data-field="problems"][data-uid="stoma-two"]'));
  await w.JasonEncounters.save();assert.match(q('[role="alert"]').textContent,/peristomal skin problem for Urostomy/);assert.equal(w.fixture.calls.length,0);
  change(w,'[data-kind="skin"][data-field="problems"][data-uid="stoma-two"][value="Mucocutaneous separation"]',true);
  assert.equal(q('[data-kind="skin"][data-field="problems"][data-uid="stoma-two"]').closest('details').open,true);
  const st=w.JasonEncounters.state.draft.stomas;assert.deepEqual(plain(st[1].complications.map(c=>[c.text,c.status])),[['Mucocutaneous separation','open']]);assert.equal(st[0].complications.length,0);
  assert.match(q('[data-section="complications:stoma-two"] summary').textContent,/Mucocutaneous separation · active/);
  change(w,'[data-kind="skin"][data-field="status"][data-uid="stoma-one"]','Healthy');
  await w.JasonEncounters.save();const a=w.fixture.calls[0].args;assert.match(a.p_report,/Urostomy — .*peristomal skin: not healthy \(Mucocutaneous separation\)/);assert.match(a.p_report,/Loop Ileostomy — .*peristomal skin: healthy/);
  const comps=JSON.parse(a.p_impact.patient_patch.complications);assert.deepEqual(comps.map(c=>[c.text,c.stoma_uid,c.status]),[['Mucocutaneous separation','stoma-two','open']]);
  click(w,'edit');change(w,'[data-kind="skin"][data-field="status"][data-uid="stoma-two"]','Healthy');assert.equal(w.JasonEncounters.state.draft.stomas[1].complications[0].status,'resolved');assert.equal(q('[data-kind="skin"][data-field="problems"][data-uid="stoma-two"]'),null);
  await w.JasonEncounters.save();assert.equal(JSON.parse(w.fixture.calls[1].args.p_impact.patient_patch.complications)[0].status,'resolved');});

test('an open skin complication on record pre-fills the peristomal skin as Not healthy',async t=>{const w=setup(t);w.fixture.patient.complications=JSON.stringify([{id:'c1',text:'Mucocutaneous separation',stoma_uid:'stoma-one',status:'open'},{id:'c2',text:'Retraction',stoma_uid:'stoma-one',status:'open'}]);
  await w.JasonEncounters.open(w.fixture.patient.id);const k=w.JasonEncounters.state.draft.stomas[0].skin;assert.deepEqual(plain(k),{status:'Not healthy',problems:['Mucocutaneous separation']});
  assert.deepEqual(plain(w.JasonEncounters.state.draft.stomas[1].skin),{status:'',problems:[]});});
