const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const {boot}=require('./jason-encounters.fixture.cjs');
const script=fs.readFileSync(path.join(__dirname,'../../assets/jason-encounters.js'),'utf8');
const plain=x=>JSON.parse(JSON.stringify(x));
const tick=()=>new Promise(r=>setTimeout(r,0));
function setup(t){const dom=new JSDOM('<div id="app"><main class="main"><section id="page-handover" class="page active"><table><tr><td>All patients</td></tr></table></section></main></div>',{runScripts:'outside-only',url:'https://example.test'});t.after(()=>dom.window.close());boot(dom.window);dom.window.eval(script);return dom.window;}
function change(w,selector,value){const el=w.document.querySelector(selector);assert.ok(el,selector);if(el.type==='checkbox')el.checked=value;else el.value=value;el.dispatchEvent(new w.Event('change',{bubbles:true}));}
function notes(w,text){const el=w.document.getElementById('jenc-notes');el.value=text;el.dispatchEvent(new w.Event('input',{bubbles:true}));}
function click(w,action,extra=''){const el=w.document.querySelector('[data-action="'+action+'"]'+extra);assert.ok(el,action);el.click();}

test('only the verified Jason profile can open the new workspace',async t=>{const w=setup(t);w.fixture.email='other@example.test';await w.JasonEncounters.open(w.fixture.patient.id);assert.equal(w.fixture.reads,0);assert.equal(w.JasonEncounters.state,null);w.fixture.email='jason.fenech@gov.mt';w.fixture.enabled=false;await w.JasonEncounters.open(w.fixture.patient.id);assert.equal(w.fixture.reads,0);});

test('opening preserves the full handover table and collapses the current appliance setup',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);assert.ok(w.document.querySelector('#page-handover table'));assert.ok(w.document.body.classList.contains('jenc-open'));const ap=w.document.querySelector('[data-section="appliances:stoma-one"]');assert.equal(ap.open,false);assert.match(ap.textContent,/Drainable pouch/);assert.match(ap.textContent,/Current setup · no changes/);assert.ok(w.document.querySelector('#jenc-notes'));assert.doesNotMatch(w.document.querySelector('#page-jason-encounters').textContent,/Assigned nurse/);});

test('each stoma retains its own assessment, output and appliance selection',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-kind="stoma"][data-field="colour"]','Healthy pink');change(w,'[data-field="output"][value="Gas"]',true);click(w,'stoma','[data-uid="stoma-two"]');change(w,'[data-kind="stoma"][data-field="colour"]','Dusky');change(w,'[data-field="output"][value="Serous fluid"]',true);const s=w.JasonEncounters.state.draft.stomas;assert.equal(s[0].colour,'Healthy pink');assert.deepEqual(plain(s[0].output),['Gas']);assert.equal(s[1].colour,'Dusky');assert.deepEqual(plain(s[1].output),['Serous fluid']);assert.deepEqual(plain(s[0].appliances),['Drainable pouch']);assert.deepEqual(plain(s[1].appliances),['Urostomy pouch']);assert.equal(w.document.querySelector('[data-kind="rod"]'),null);});

test('Nil is exclusive, other outputs can be combined, and the dropdown stays open',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-field="output"][value="Liquid"]',true);change(w,'[data-field="output"][value="Gas"]',true);assert.deepEqual(plain(w.JasonEncounters.state.draft.stomas[0].output),['Liquid','Gas']);change(w,'[data-field="output"][value="Nil"]',true);assert.deepEqual(plain(w.JasonEncounters.state.draft.stomas[0].output),['Nil']);change(w,'[data-field="output"][value="Blood"]',true);assert.deepEqual(plain(w.JasonEncounters.state.draft.stomas[0].output),['Blood']);assert.equal(w.document.querySelector('[data-field="output"]').closest('details').open,true);});

test('notes save exact text, episode and selected stomas with automatic signature, without appliance writes',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-kind="global"][value="stoma-two"]',false);notes(w,'Patient comfortable.\nTeaching given <today>.');await w.JasonEncounters.save();const args=w.fixture.calls[0].args;assert.equal(args.p_episode_id,w.fixture.episode.id);assert.deepEqual(args.p_snapshot.scope,['stoma-one']);assert.equal(args.p_snapshot.notes,'Patient comfortable.\nTeaching given <today>.');assert.deepEqual(args.p_impact.appliances,[]);assert.deepEqual(args.p_impact.patient_patch,{});assert.equal(w.JasonEncounters.state.editable,false);assert.match(w.document.querySelector('.jenc-signature').textContent,/Signed by: Jason Fenech/);assert.equal(w.document.querySelector('#jenc-report today'),null);});

test('editing saved wording and a dropdown makes V2 on the same encounter with only changes red',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-field="colour"]','Healthy pink');notes(w,'Patient comfotable today.');await w.JasonEncounters.save();const id=w.JasonEncounters.state.record.id;click(w,'edit');notes(w,'Patient comfortable today.');change(w,'[data-field="colour"]','Dusky');assert.equal(w.document.querySelector('#jenc-note-mirror .jenc-change').textContent,'comfortable');assert.ok(w.document.querySelector('[data-field="colour"]').classList.contains('jenc-changed'));assert.match(w.document.querySelector('#jenc-note-diff del').textContent,/comfotable/);await w.JasonEncounters.save();const state=w.JasonEncounters.state;assert.equal(state.record.id,id);assert.equal(state.record.assessment.versions.length,2);assert.equal(state.record.assessment.versions[0].snapshot.notes,'Patient comfotable today.');assert.equal(state.record.assessment.versions[0].snapshot.stomas[0].colour,'Healthy pink');assert.equal(w.fixture.calls[1].args.p_encounter_id,id);assert.equal(w.fixture.calls[1].args.p_expected_version,1);assert.equal(state.expectedVersion,2);click(w,'version','[data-index="0"]');assert.equal(w.document.getElementById('jenc-notes').value,'Patient comfotable today.');assert.equal(w.document.querySelector('[data-field="colour"]').value,'Healthy pink');assert.equal(w.document.querySelector('#jenc-note-mirror .jenc-change'),null);});

test('a failed save keeps the editable draft and leaves appliances untouched for retry',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);notes(w,'Keep this draft.');w.fixture.failSave=true;await w.JasonEncounters.save();assert.equal(w.JasonEncounters.state.editable,true);assert.equal(w.document.getElementById('jenc-notes').value,'Keep this draft.');assert.match(w.document.querySelector('[role="alert"]').textContent,/changes remain/);assert.equal(w.document.getElementById('jenc-save').disabled,false);assert.equal(w.fixture.records.length,0);assert.deepEqual(w.fixture.calls[0].args.p_impact.appliances,[]);});

test('an appliance edit affects one stoma, and a two-piece system requires both pieces',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-field="pouch"]','Convex drainable pouch');await w.JasonEncounters.save();assert.equal(w.fixture.calls[0].args.p_impact.appliances.length,1);assert.equal(w.fixture.calls[0].args.p_impact.appliances[0].stoma_uid,'stoma-one');assert.deepEqual(w.fixture.calls[0].args.p_snapshot.stomas[1].appliances,['Urostomy pouch']);click(w,'edit');change(w,'[data-field="system"]','two');change(w,'[data-field="baseplate"]','Baseplate 57 mm');await w.JasonEncounters.save();assert.equal(w.fixture.calls.length,1);assert.match(w.document.querySelector('[role="alert"]').textContent,/both the baseplate and pouch/);});

test('patient infection, episode support and per-stoma complications all enter the saved report',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);change(w,'[data-kind="infection"][data-field="status"]','Infection');change(w,'[data-kind="infection"][data-field="organism"]','CRE');click(w,'add-referral');change(w,'[data-kind="referral"][data-field="profession"]','Psychologist');change(w,'[data-kind="referral"][data-field="status"]','Seen');click(w,'add-comp');change(w,'[data-kind="comp"][data-field="text"]','Retraction');await w.JasonEncounters.save();const a=w.fixture.calls[0].args;assert.match(a.p_report,/CRE · Infection/);assert.match(a.p_report,/Psychologist: seen/);assert.match(a.p_report,/Retraction: active/);const comps=JSON.parse(a.p_impact.patient_patch.complications);assert.equal(comps[0].stoma_uid,'stoma-one');assert.equal(a.p_snapshot.stomas[1].complications.length,0);});

test('unchanged edits create no extra version and read-only history still allows filtering',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);notes(w,'Assessment complete.');await w.JasonEncounters.save();click(w,'edit');await w.JasonEncounters.save();assert.equal(w.fixture.calls.length,1);assert.match(w.document.querySelector('[role="alert"]').textContent,/no changes/);click(w,'cancel');click(w,'history');const filter=w.document.querySelector('[data-kind="history"]');assert.equal(filter.disabled,false);change(w,'[data-kind="history"]','all');assert.equal(w.document.querySelectorAll('[data-action="view"]').length,1);});

test('Jason handover retains status summaries and print values with only the Encounter care action',t=>{const w=setup(t);w.applianceLineIsTwoPiece=()=>true;w.handoverComplicationLine=()=> 'Retraction';w.fixture.patient.flange_due='2026-10-07';w.fixture.patient.inpatient_nurse_notes='CRE · Infection';const cell=w.JasonEncounters.handoverCell(w.fixture.patient,'Two-piece pouch');const el=w.document.createElement('div');el.innerHTML=cell;assert.equal(el.querySelectorAll('button').length,1);assert.match(el.querySelector('button').textContent,/Encounter/);assert.equal(el.querySelector('.hv-appl').tagName,'SPAN');assert.equal(el.querySelector('.hv-appl').getAttribute('onclick'),null);assert.equal(el.querySelector('.hv-flange-date').type,'hidden');assert.equal(el.querySelector('.hv-flange-date').value,'2026-10-07');assert.equal(el.querySelector('.hv-note').value,'CRE · Infection');assert.equal(el.querySelector('.hv-cmp-line').textContent,'Retraction');});

test('a discharged patient can still open, read and correct saved encounter history',async t=>{const w=setup(t);await w.JasonEncounters.open(w.fixture.patient.id);notes(w,'Before discharge.');await w.JasonEncounters.save();w.fixture.episode.is_current=false;w.fixture.episode.discharge_date='2026-10-05';await w.JasonEncounters.open(w.fixture.patient.id);assert.equal(w.JasonEncounters.state.mode,'history');assert.equal(w.document.querySelector('[data-action="new"]').disabled,true);click(w,'view');assert.equal(w.document.getElementById('jenc-notes').value,'Before discharge.');click(w,'edit');notes(w,'Corrected before discharge.');await w.JasonEncounters.save();assert.equal(w.JasonEncounters.state.record.assessment.versions.length,2);assert.equal(w.JasonEncounters.state.rows.length,1);});
