const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const {JSDOM}=require('jsdom');
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');
function source(name){const m=html.match(new RegExp('(?:async )?function '+name+'\\('));assert(m,name);const start=m.index;const end=html.indexOf('\n}',start);return html.slice(start,end+2);}
function context(){
 const dom=new JSDOM('<body><div id="mo"></div><div id="mb"></div></body>');
 const c=vm.createContext({document:dom.window.document,TODAY:'2026-09-25',Date,console,htmlSafe:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),fmtShortDate:s=>s,prettyStomaType:s=>s,initialStomaCode:s=>'ID-'+s,newStomaUid:()=> 'draft-uid',sexModalClass:()=>'',openMo:()=>{},confirm:()=>true,closeModalGuarded:()=>{},normaliseFollowupStatus:s=>s||'active',patientIsDeceased:p=>!!p.deceased_date,shortApplianceList:a=>a||[],stomaShortType:t=>t,stomaQuadrant:()=>'',collectStomaTargetsFromPatient:()=>[],stomaTypeOptions:t=>`<option>${t||'End colostomy'}</option>`,stomaLocOptions:t=>`<option>${t||'Existing location'}</option>`});
 for(const name of ['parseStomas','parseRefashionings','parseInitialStomas','stomaOperationHistory','stomaOperationFingerprint','patientStomaList','stomaTimeline','stomasPresentOn','buildStomaOperationPatch','currentApplianceNoteRows','handoverApplianceRowText','handoverStomaLine','handoverOperationSummary','previousStomaRecords','stomaRecordsFor','operationTargetLabel','openStomaOperation','changeStomaOperationTarget','changeStomaOperationKind','readStomaOperation','stomaOperationError','reviewStomaOperation','backStomaOperation','saveStomaOperation'])vm.runInContext(source(name),c);
 vm.runInContext('let stomaOperationCtx=null;let PF_STOMA_TARGETS=[];let modalCloseGuard=null;',c);
 return c;
}
const patient=()=>({id:'p1',stoma_type:'End colostomy',stoma_location:'LIF',surgery_date:'2026-01-01',followup_status:'active',extra_stomas:[],extra_refashionings:[],initial_stomas:[],stoma_operation_history:[]});
const draft=(kind='refashion')=>({kind,uid:'new-id',target_uid:'base',date:'2026-09-25',date_unknown:false,type:'End colostomy',location:'LIF',operation:'Procedure and findings',same_admission:true,admission_answer:'yes',outcomes:[],discharge_date:null});
test('refashion creates a fresh linked ID, retaining prior history and one present stoma',()=>{const c=context(),p=patient(),patch=c.buildStomaOperationPatch(p,draft());assert.equal(patch.extra_refashionings[0].target_uid,'base');assert.equal(patch.extra_refashionings[0].uid,'new-id');assert.equal(patch.reversal_date,undefined);assert.equal(patch.extra_stomas,undefined);assert.equal(p.extra_refashionings.length,0);const list=c.patientStomaList({...p,...patch});assert.equal(list.filter(x=>x.present).length,1);assert.equal(list.find(x=>x.uid==='base').superseded,true);});
test('a refashioned stoma can itself be refashioned; appliance choices use only the latest ID',()=>{const c=context();let p=patient();p={...p,...c.buildStomaOperationPatch(p,draft())};p={...p,...c.buildStomaOperationPatch(p,{...draft(),uid:'third-id',target_uid:'new-id'})};assert.deepEqual(Array.from(c.patientStomaList(p).filter(x=>x.present),x=>x.uid),['third-id']);assert.deepEqual(Array.from(c.stomasPresentOn(p,'2026-09-25'),x=>x.uid),['third-id']);});
test('combined reversal and new stoma stays active; unaffected stomas stay present',()=>{const c=context(),p=patient();const patch=c.buildStomaOperationPatch(p,{...draft('new'),outcomes:[{uid:'base',state:'reversed'}]});assert.equal(patch.reversal_date,'2026-09-25');assert.equal(patch.followup_status,'active');assert.equal(c.patientStomaList({...p,...patch}).filter(x=>x.present).length,1);const two=c.buildStomaOperationPatch(p,{...draft('new'),outcomes:[{uid:'base',state:'present'}]});assert.equal(c.patientStomaList({...p,...two}).filter(x=>x.present).length,2);});
test('unknown reversal date is not invented and does not leave stoma present',()=>{const c=context(),p=patient();const patch=c.buildStomaOperationPatch(p,{...draft('reversal'),date:null,date_unknown:true});assert.equal(patch.reversal_date,null);assert.equal(patch.followup_status,'reversed');assert.equal(c.patientStomaList({...p,...patch})[0].reversal_unknown,true);});
test('handover never carries an old appliance or flange due to the refashioned stoma',()=>{const c=context(),p=patient();const updated={...p,...c.buildStomaOperationPatch(p,draft())};const old=[{stoma_uid:'base',appliances:['Old pouch'],flange_due:'2026-09-26',changed_on:'2026-09-25'}];const line=c.handoverStomaLine(updated,old);assert.match(line,/refashioned/);assert.match(line,/Appliance not yet selected/);assert.doesNotMatch(line,/Old pouch|flange due/);assert.equal(c.currentApplianceNoteRows(updated,old).length,0);const current=c.handoverStomaLine(updated,[...old,{stoma_uid:'new-id',appliances:['New pouch'],changed_on:'2026-09-25'}]);assert.match(current,/New pouch/);assert.doesNotMatch(current,/Old pouch/);assert.match(c.handoverOperationSummary(updated),/Refashioning/);});
test('legacy flat clinic appliances are not offered to a refashioned ID',()=>{const c=context();c.parseNameList=x=>x||[];const rows=c.previousStomaRecords([{id:'a1',appliances:['Old pouch'],accessories:[]}],null,[{uid:'new-id',origin:'refashion'}]);assert.equal(rows['new-id'],undefined);});
test('opening and reviewing a draft performs no write and preserves location control',async()=>{const c=context();let writes=0;c.fetchPatientById=async()=>({data:patient()});c.SB={from:()=>{writes++;throw Error('Unexpected write');}};await c.openStomaOperation('p1','refashion');assert.equal(writes,0);const d=c.document;assert.equal(d.getElementById('so-location').value,'LIF');d.getElementById('so-date').value='2026-09-25';d.getElementById('so-findings').value='Procedure';d.getElementById('so-admission').value='yes';c.stomaBadgesHTML=x=>x.present?'Present':'History';c.reviewStomaOperation();assert.equal(d.getElementById('so-details').hidden,true);assert.equal(writes,0);c.backStomaOperation();assert.equal(d.getElementById('so-details').hidden,false);});
test('invalid chronology and missing refashion target are blocked',()=>{const c=context();assert.throws(()=>c.buildStomaOperationPatch(patient(),{...draft(),date:'2025-01-01'}),/before/);assert.throws(()=>c.buildStomaOperationPatch(patient(),{...draft(),target_uid:'absent'}),/Choose the present/);});
test('save is one guarded update; an inpatient refashioning opens appliance selection',async()=>{const c=context(),p={...patient(),is_inpatient:true};let writes=0,appliance=0,closed=0;const filters=[];c.fetchPatientById=async()=>({data:p});c.stomaBadgesHTML=x=>x.present?'Present':'History';c.SB={from:()=>({update:patch=>{writes++;assert.equal(patch.extra_refashionings[0].uid,'draft-uid');return{eq:(k,v)=>{filters.push([k,v]);return query;}};}})};const query={eq:(k,v)=>{filters.push([k,v]);return query;},select:()=>({single:async()=>({data:{id:'p1'}})})};c.closeModal=()=>closed++;c.refreshReminders=()=>{};c.afterStomaSaved=async()=>{};c.openHandoverAppliance=async()=>appliance++;await c.openStomaOperation('p1','refashion');const d=c.document;d.getElementById('so-date').value='2026-09-25';d.getElementById('so-findings').value='Refashioned';d.getElementById('so-admission').value='yes';c.reviewStomaOperation();await Promise.all([c.saveStomaOperation(),c.saveStomaOperation()]);assert.equal(writes,1);assert.equal(closed,1);assert.equal(appliance,1);assert(filters.some(([k])=>k==='stoma_operation_history'));});
test('missing migration blocks the entire operation with an actionable error',async()=>{const c=context();c.fetchPatientById=async()=>({data:patient()});c.stomaBadgesHTML=()=>'';const query={eq:()=>query,select:()=>({single:async()=>({error:{message:'stoma_operation_history column missing'}})})};c.SB={from:()=>({update:()=>query})};await c.openStomaOperation('p1','reversal');const d=c.document;d.getElementById('so-unknown').checked=true;d.getElementById('so-findings').value='Reversal';c.reviewStomaOperation();await c.saveStomaOperation();assert.match(d.getElementById('so-error').textContent,/Nothing from this operation has been saved/);assert.equal(d.getElementById('so-save').disabled,false);});
